- package:
    name:
      - amazon-ecr-credential-helper
    state: latest
    update_cache: true
  become: yes

- ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.docker"
    state: directory

- ansible.builtin.copy:
    src: config.json
    dest: "/home/{{ ansible_user }}/.docker/config.json"

- ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.aws"
    state: directory

- blockinfile:
    path: "/home/{{ ansible_user }}/.aws/credentials"
    create: yes
    block: |
      [{{ aws_ecr_user }}]
      aws_access_key_id = {{ aws_ecr_user_access_key_id }}
      aws_secret_access_key = {{ aws_ecr_user_secret_access_key }}
    marker: "# {mark} ecr user"

- blockinfile:
    path: "/home/{{ ansible_user }}/.aws/config"
    create: yes
    block: |
      [profile {{ aws_ecr_user }}]
      region = {{ aws_ecr_region }}
      output = json
    marker: "# {mark} ecr user"
