all:
  children:
    jukebox_cluster:
      hosts:
        jukebox[1:2].us-west-1.yag.vm:
      vars:
        appstor_internal_ip: "192.168.56.110" # sync-up with Vagrantfile        
    appstor:
      hosts:
        appstor1.us-west-1.yag.vm:
  vars:
    cluster_region: "us-west-1"
