- package:
      name:
          - dnsutils
      state: latest
      update_cache: true

- ansible.builtin.lineinfile:
      path: /etc/dhcp/dhclient.conf
      line: "supersede domain-name-servers 1.1.1.1, 8.8.8.8;"
      state: present
      create: yes

- ansible.builtin.blockinfile:
      path: /etc/systemd/resolved.conf
      block: |
          [Resolve]
          DNS=1.1.1.1 8.8.8.8
          FallbackDNS=9.9.9.9 8.8.4.4

- ansible.builtin.file:
      src: "/run/systemd/resolve/stub-resolv.conf"
      path: "/etc/resolv.conf"
      force: "yes"
      state: "link"
      follow: false

- ansible.builtin.service:
      name: "systemd-resolved"
      state: restarted
      enabled: true
