- name: secure ssh access
  ansible.builtin.copy:
    src: ssh/sshd_config
    dest: /etc/ssh/sshd_config

- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: add infras' user key into allowed list
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', 'ssh/{{ infra_env }}/id_ed25519.pub') }}"
    state: present

