meshConfig:
  accessLogEncoding: JSON
  accessLogFile: /dev/stdout
  defaultConfig:
    gatewayTopology:
      # proxyProtocol: {}
      numTrustedProxies: 1
  extensionProviders:
    - name: ext-authz-http
      envoyExtAuthzHttp:
        headersToUpstreamOnAllow:
          - x-auth-uid
        includeRequestHeadersInCheck:
          - cookie
        pathPrefix: /auth/verify
        port: 80
        service: ${authsvc}
  ingressSelector: ${gw_selector}
  ingressService: ${gw_name}
