- name: parent roles
  include_role:
    name: "{{ appstor_parent_roles_item }}"
  with_items: "{{ parent_roles }}"
  loop_control:
    loop_var: appstor_parent_roles_item

- name: install deps
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - rsync
    - btrfs-progs
    - gettext-base

- ansible.builtin.file:
    path: "{{ app_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- ansible.builtin.copy:
    src: "exports"
    dest: "{{ app_path }}/exports"
    owner: root
    group: root
    mode: "0644"

- name: check if bees is already installed
  stat:
    path: /sbin/beesd
  register: beesd

- name: build and install bees deduplication daemon
  block:
    - ansible.builtin.git:
        repo: https://github.com/Zygo/bees.git
        dest: /tmp/bees
        single_branch: yes
        version: v0.11
    - make:
        chdir: /tmp/bees
        target: install
    - ansible.builtin.copy:
        src: /tmp/bees/scripts/beesd@.service
        dest: /etc/systemd/system/beesd@.service
        remote_src: true
  when: not beesd.stat.exists

- name: add primary appstor node key into authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', 'files/secrets/id_ed25519.pub') }}"
    state: present

- ansible.builtin.copy:
    src: "clone_app.sh"
    dest: "{{ app_path }}/clone_app.sh"
    owner: 1000
    group: 1000
    mode: '0755'

- name: pre-pull NFS server docker image so first boot does not need to download it
  community.docker.docker_image:
    name: erichough/nfs-server@sha256:784ef30907aa318b8324c4c49bd258b11a740ab0eea9f09b5ccf9df378fa77ca
    source: pull

- import_tasks: install_firstboot.yml
