- include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: ensure docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: add user to docker group
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

# refresh groups
- name: reset ssh connection
  ansible.builtin.meta: reset_connection
