all:
  children:
    jukebox_cluster:
      hosts:
        192.168.13.2:
      vars:
        appstor_internal_ip: "192.168.13.200"
    appstor:
      hosts:
        192.168.13.200:
  vars:
    cluster_region: "us-west-1"
    ansible_python_interpreter: /usr/bin/python3
