all:
  children:
    jukebox:
      hosts:
        jukebox0-us-east-1:
      vars:
        appstor_internal_ip: "appstor0-us-east-1"
        fqdn_host_prefix: "jukebox"
        fqdn_host_group: "jukebox"
    appstor:
      hosts:
        appstor0-us-east-1:
      vars:
        fqdn_host_prefix: "appstor"
        fqdn_host_group: "appstor"
    appstor_master:
      hosts:
        appstor0-us-east-1:
  vars:
    cluster_region: "us-east-1"
    ansible_python_interpreter: /usr/bin/python3
